GoetasWebservices\Client\SalesforceEnterprise\Sobject\AuthConfigProvidersType:
    properties:
        authConfig:
            expose: true
            access_type: public_method
            serialized_name: AuthConfig
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getAuthConfig
                setter: setAuthConfig
            type: GoetasWebservices\Client\SalesforceEnterprise\Sobject\AuthConfigType
        authConfigId:
            expose: true
            access_type: public_method
            serialized_name: AuthConfigId
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getAuthConfigId
                setter: setAuthConfigId
            type: string
        authProvider:
            expose: true
            access_type: public_method
            serialized_name: AuthProvider
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getAuthProvider
                setter: setAuthProvider
            type: GoetasWebservices\Client\SalesforceEnterprise\Sobject\SObjectType
        authProviderId:
            expose: true
            access_type: public_method
            serialized_name: AuthProviderId
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getAuthProviderId
                setter: setAuthProviderId
            type: string
        createdBy:
            expose: true
            access_type: public_method
            serialized_name: CreatedBy
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getCreatedBy
                setter: setCreatedBy
            type: GoetasWebservices\Client\SalesforceEnterprise\Sobject\UserType
        createdById:
            expose: true
            access_type: public_method
            serialized_name: CreatedById
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getCreatedById
                setter: setCreatedById
            type: string
        createdDate:
            expose: true
            access_type: public_method
            serialized_name: CreatedDate
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getCreatedDate
                setter: setCreatedDate
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        isDeleted:
            expose: true
            access_type: public_method
            serialized_name: IsDeleted
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getIsDeleted
                setter: setIsDeleted
            type: bool
        lastModifiedBy:
            expose: true
            access_type: public_method
            serialized_name: LastModifiedBy
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getLastModifiedBy
                setter: setLastModifiedBy
            type: GoetasWebservices\Client\SalesforceEnterprise\Sobject\UserType
        lastModifiedById:
            expose: true
            access_type: public_method
            serialized_name: LastModifiedById
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getLastModifiedById
                setter: setLastModifiedById
            type: string
        lastModifiedDate:
            expose: true
            access_type: public_method
            serialized_name: LastModifiedDate
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getLastModifiedDate
                setter: setLastModifiedDate
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        systemModstamp:
            expose: true
            access_type: public_method
            serialized_name: SystemModstamp
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getSystemModstamp
                setter: setSystemModstamp
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
