GoetasWebservices\Client\SalesforceEnterprise\Sobject\ChatterExtensionConfigType:
    properties:
        canCreate:
            expose: true
            access_type: public_method
            serialized_name: CanCreate
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getCanCreate
                setter: setCanCreate
            type: bool
        canRead:
            expose: true
            access_type: public_method
            serialized_name: CanRead
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getCanRead
                setter: setCanRead
            type: bool
        chatterExtension:
            expose: true
            access_type: public_method
            serialized_name: ChatterExtension
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getChatterExtension
                setter: setChatterExtension
            type: GoetasWebservices\Client\SalesforceEnterprise\Sobject\ChatterExtensionType
        chatterExtensionId:
            expose: true
            access_type: public_method
            serialized_name: ChatterExtensionId
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getChatterExtensionId
                setter: setChatterExtensionId
            type: string
        createdBy:
            expose: true
            access_type: public_method
            serialized_name: CreatedBy
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getCreatedBy
                setter: setCreatedBy
            type: GoetasWebservices\Client\SalesforceEnterprise\Sobject\UserType
        createdById:
            expose: true
            access_type: public_method
            serialized_name: CreatedById
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getCreatedById
                setter: setCreatedById
            type: string
        createdDate:
            expose: true
            access_type: public_method
            serialized_name: CreatedDate
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getCreatedDate
                setter: setCreatedDate
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        isDeleted:
            expose: true
            access_type: public_method
            serialized_name: IsDeleted
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getIsDeleted
                setter: setIsDeleted
            type: bool
        lastModifiedBy:
            expose: true
            access_type: public_method
            serialized_name: LastModifiedBy
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getLastModifiedBy
                setter: setLastModifiedBy
            type: GoetasWebservices\Client\SalesforceEnterprise\Sobject\UserType
        lastModifiedById:
            expose: true
            access_type: public_method
            serialized_name: LastModifiedById
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getLastModifiedById
                setter: setLastModifiedById
            type: string
        lastModifiedDate:
            expose: true
            access_type: public_method
            serialized_name: LastModifiedDate
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getLastModifiedDate
                setter: setLastModifiedDate
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        position:
            expose: true
            access_type: public_method
            serialized_name: Position
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getPosition
                setter: setPosition
            type: int
        systemModstamp:
            expose: true
            access_type: public_method
            serialized_name: SystemModstamp
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getSystemModstamp
                setter: setSystemModstamp
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
