GoetasWebservices\Client\SalesforceEnterprise\Sobject\UserProvisioningConfigType:
    properties:
        approvalRequired:
            expose: true
            access_type: public_method
            serialized_name: ApprovalRequired
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getApprovalRequired
                setter: setApprovalRequired
            type: string
        connectedApp:
            expose: true
            access_type: public_method
            serialized_name: ConnectedApp
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getConnectedApp
                setter: setConnectedApp
            type: GoetasWebservices\Client\SalesforceEnterprise\Sobject\ConnectedApplicationType
        connectedAppId:
            expose: true
            access_type: public_method
            serialized_name: ConnectedAppId
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getConnectedAppId
                setter: setConnectedAppId
            type: string
        createdBy:
            expose: true
            access_type: public_method
            serialized_name: CreatedBy
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getCreatedBy
                setter: setCreatedBy
            type: GoetasWebservices\Client\SalesforceEnterprise\Sobject\UserType
        createdById:
            expose: true
            access_type: public_method
            serialized_name: CreatedById
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getCreatedById
                setter: setCreatedById
            type: string
        createdDate:
            expose: true
            access_type: public_method
            serialized_name: CreatedDate
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getCreatedDate
                setter: setCreatedDate
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        developerName:
            expose: true
            access_type: public_method
            serialized_name: DeveloperName
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getDeveloperName
                setter: setDeveloperName
            type: string
        enabled:
            expose: true
            access_type: public_method
            serialized_name: Enabled
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getEnabled
                setter: setEnabled
            type: bool
        enabledOperations:
            expose: true
            access_type: public_method
            serialized_name: EnabledOperations
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getEnabledOperations
                setter: setEnabledOperations
            type: string
        isDeleted:
            expose: true
            access_type: public_method
            serialized_name: IsDeleted
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getIsDeleted
                setter: setIsDeleted
            type: bool
        language:
            expose: true
            access_type: public_method
            serialized_name: Language
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getLanguage
                setter: setLanguage
            type: string
        lastModifiedBy:
            expose: true
            access_type: public_method
            serialized_name: LastModifiedBy
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getLastModifiedBy
                setter: setLastModifiedBy
            type: GoetasWebservices\Client\SalesforceEnterprise\Sobject\UserType
        lastModifiedById:
            expose: true
            access_type: public_method
            serialized_name: LastModifiedById
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getLastModifiedById
                setter: setLastModifiedById
            type: string
        lastModifiedDate:
            expose: true
            access_type: public_method
            serialized_name: LastModifiedDate
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getLastModifiedDate
                setter: setLastModifiedDate
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        lastReconDateTime:
            expose: true
            access_type: public_method
            serialized_name: LastReconDateTime
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getLastReconDateTime
                setter: setLastReconDateTime
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        masterLabel:
            expose: true
            access_type: public_method
            serialized_name: MasterLabel
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getMasterLabel
                setter: setMasterLabel
            type: string
        namedCredential:
            expose: true
            access_type: public_method
            serialized_name: NamedCredential
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getNamedCredential
                setter: setNamedCredential
            type: GoetasWebservices\Client\SalesforceEnterprise\Sobject\NamedCredentialType
        namedCredentialId:
            expose: true
            access_type: public_method
            serialized_name: NamedCredentialId
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getNamedCredentialId
                setter: setNamedCredentialId
            type: string
        namespacePrefix:
            expose: true
            access_type: public_method
            serialized_name: NamespacePrefix
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getNamespacePrefix
                setter: setNamespacePrefix
            type: string
        notes:
            expose: true
            access_type: public_method
            serialized_name: Notes
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getNotes
                setter: setNotes
            type: string
        onUpdateAttributes:
            expose: true
            access_type: public_method
            serialized_name: OnUpdateAttributes
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getOnUpdateAttributes
                setter: setOnUpdateAttributes
            type: string
        reconFilter:
            expose: true
            access_type: public_method
            serialized_name: ReconFilter
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getReconFilter
                setter: setReconFilter
            type: string
        systemModstamp:
            expose: true
            access_type: public_method
            serialized_name: SystemModstamp
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getSystemModstamp
                setter: setSystemModstamp
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        userAccountMapping:
            expose: true
            access_type: public_method
            serialized_name: UserAccountMapping
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getUserAccountMapping
                setter: setUserAccountMapping
            type: string
