GoetasWebservices\Client\SalesforceEnterprise\Sobject\FiscalYearSettingsType:
    properties:
        description:
            expose: true
            access_type: public_method
            serialized_name: Description
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getDescription
                setter: setDescription
            type: string
        endDate:
            expose: true
            access_type: public_method
            serialized_name: EndDate
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getEndDate
                setter: setEndDate
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Date
        isStandardYear:
            expose: true
            access_type: public_method
            serialized_name: IsStandardYear
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getIsStandardYear
                setter: setIsStandardYear
            type: bool
        name:
            expose: true
            access_type: public_method
            serialized_name: Name
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getName
                setter: setName
            type: string
        periodId:
            expose: true
            access_type: public_method
            serialized_name: PeriodId
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getPeriodId
                setter: setPeriodId
            type: string
        periodLabelScheme:
            expose: true
            access_type: public_method
            serialized_name: PeriodLabelScheme
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getPeriodLabelScheme
                setter: setPeriodLabelScheme
            type: string
        periodPrefix:
            expose: true
            access_type: public_method
            serialized_name: PeriodPrefix
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getPeriodPrefix
                setter: setPeriodPrefix
            type: string
        periods:
            expose: true
            access_type: public_method
            serialized_name: Periods
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getPeriods
                setter: setPeriods
            type: GoetasWebservices\Client\SalesforceEnterprise\Types\QueryResultType
        quarterLabelScheme:
            expose: true
            access_type: public_method
            serialized_name: QuarterLabelScheme
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getQuarterLabelScheme
                setter: setQuarterLabelScheme
            type: string
        quarterPrefix:
            expose: true
            access_type: public_method
            serialized_name: QuarterPrefix
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getQuarterPrefix
                setter: setQuarterPrefix
            type: string
        startDate:
            expose: true
            access_type: public_method
            serialized_name: StartDate
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getStartDate
                setter: setStartDate
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Date
        systemModstamp:
            expose: true
            access_type: public_method
            serialized_name: SystemModstamp
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getSystemModstamp
                setter: setSystemModstamp
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        weekLabelScheme:
            expose: true
            access_type: public_method
            serialized_name: WeekLabelScheme
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getWeekLabelScheme
                setter: setWeekLabelScheme
            type: string
        weekStartDay:
            expose: true
            access_type: public_method
            serialized_name: WeekStartDay
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getWeekStartDay
                setter: setWeekStartDay
            type: int
        yearType:
            expose: true
            access_type: public_method
            serialized_name: YearType
            xml_element:
                namespace: 'urn:sobject.enterprise.soap.sforce.com'
            accessor:
                getter: getYearType
                setter: setYearType
            type: string
