GoetasWebservices\Client\SalesforceEnterprise\Types\SoapParts\DescribeKnowledgeSettingsInput:
    xml_root_namespace: 'urn:enterprise.soap.sforce.com'
    properties:
        parameters:
            expose: true
            access_type: public_method
            accessor:
                getter: getParameters
                setter: setParameters
            xml_element:
                namespace: 'urn:enterprise.soap.sforce.com'
            serialized_name: describeKnowledgeSettings
            type: GoetasWebservices\Client\SalesforceEnterprise\Types\DescribeKnowledgeSettings
